#!/bin/bash
#
# Force checkout to lateset main/master branch from origin
# "origin" can be overridden by giving the custom name as the 1st argument
#
set -eu -o pipefail

git remote update
DEFAULT_BRANCH=master
DEFAULT_BRANCH="$(git config --get init.defaultBranch || echo "$DEFAULT_BRANCH")"
git chechout -B "$DEFAULT_BRANCH" "${1:-origin}"/"$DEFAULT_BRANCH"
