#!/bin/bash
#
# Setup simple aliases
#
set -eu -o pipefail
if [[ $# == 2 ]]
then
    exec git config --global alias."$1" "$2"
else
    echo 'usage: git alias <new alias> <original command>' >&2
    echo '  e.g. git alias ss "short -s"' >&2
    exit 1
fi
