#!/bin/bash -i
set -ef -o pipefail
shopt -s expand_aliases

CMD="${1:-}"
case "$CMD" in
    "")
        echo "Tell me what executable to search for!"
        exit 1
        ;;
    --complete)
        # alias   Alias names.  May also be specified as -a.
        # builtin Names of shell builtin commands.  May also be specified as -b.
        # command Command names.  May also be specified as -c.
        CMD="$(basename ${BASH_SOURCE[0]})"
        echo "complete -ac $CMD"
        exit
        ;;
esac

EDIT_CMD=("${EDITOR:-vim}")
EXE="$(command -v $CMD)" || command -V "$CMD"

case "$EXE" in
    "$CMD")
        # Probably a function
        EXE="$(command -V $CMD | head -1)"
        case "$EXE" in
            "$CMD is a shell builtin")
                EDIT_CMD=(man "$CMD")
                ;;
            "$CMD is a function")
                EDIT_CMD+=("+/$CMD" "$HOME"/.bashrc)
                ;;
            *)
                echo "Not sure how to handle:"
                command -V "$CMD"
                exit 1
                ;;
        esac
        ;;
    "alias $CMD"=*)
        EDIT_CMD+=("+/alias $CMD=" "$HOME"/.bashrc)
        ;;
    *)
        case "$(file -L --mime-encoding $CMD)" in
            binay)
                EDIT_CMD=(man "$CMD")
                ;;
            *)
                EDIT_CMD+=("$EXE")
                ;;
        esac
        ;;
esac
exec "${EDIT_CMD[@]}"
